<a href="https://colab.research.google.com/github/bitriagaleonela40-cmd/housing-research/blob/main/Housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [139]:
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [140]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [145]:
housing_df = pd.read_csv("/content/2022 LIHTC Full Tenant Data.csv")
housing_df

,Unnamed: 0,matching_hud_id,pin,state,propertyname,city,HH_RACE_WHITE_PCT,HH_RACE_BLACK_PCT,HH_RACE_AMINDALNAT_PCT,HH_RACE_ASIAN_PCT,...,UNITS_FRA_RPTD_GRT0_PCT,UNITS_FRA_SRC_PBRA_PCT,UNITS_FRA_SRC_S8_PCT,UNITS_FRA_SRC_PH_PCT,UNITS_FRA_SRC_HOME_PCT,UNITS_FRA_SRC_HCV_PCT,UNITS_FRA_SRC_PBV_PCT,UNITS_FRA_SRC_S521_PCT,UNITS_FRA_SRC_OTHER_PCT,UNITS_FRA_SRC_MSSNG_PCT
0,1,AKA20049041,AK-99-99,AK,BAYVIEW APTS. ASSOC. LP,SEWARD,91.300003,-4.0,-4.0,0.0,...,91.300003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
1,2,AKA20049041,AK-99-99,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,46.299999,-4.0,-4.0,-4.0,...,97.599998,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
2,3,AKA20049041,AK-99-99,AK,EAGLE RIDGE OF PALMER,PALMER,87.500000,-4.0,-4.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,AKA20049041,AK-99-99,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD,90.900002,-4.0,0.0,0.0,...,95.500000,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
4,5,AKA20049041,AK-99-99,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN,76.099998,-4.0,-4.0,-4.0,...,97.800003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38223,38224,NaN,NaN,WY,PINEWOOD APARTMENTS,MARBLETON,NaN,NaN,NaN,NaN,...,-4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38224,38225,NaN,NaN,NM,PASA TIEMPO,SANTE FE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38225,38226,NaN,NaN,SD,SICANGU VILLAGE ESTATES III,VALENTINE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38226,38227,NaN,NaN,VA,BICKERSTAFF CROSSING,HENRICO,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38227,38228,NaN,NaN,WA,TEAL POINTE APARTMENTS,VANCOUVER,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

I belive I have 38228 rows and 47 colunms

Interpeting the first five rows
I learned that .xlsx stands for a excel file and therefore I cannot use read_csv. Instead I can use pd.read_excel to load in my data set. Looking at this data set, Im noticing that it mathces my housing_df, the only difference is it does not include any varibles past city. This can be useful if I want to limit myself to look at only  thouse variables.

Data sets can help investors to gauge assistance need and then invest.

Colums 1-5 in the housing_df come from this df.

In [142]:
url = "https://github.com/frontiertechinstitute/datasets/raw/main/2022%20LIHTC%20Tenant%20Data/data/2022%20LIHTC%20Tenant%20Data%20by%20Property%20-%20HUD_ID.xlsx"
df = pd.read_excel(url)
df.head(5)
df[['matching_hud_id', 'pin', 'state', 'propertyname', 'city']]

,matching_hud_id,pin,state,propertyname,city
0,AKA20049041,AK-99-99,AK,BAYVIEW APTS. ASSOC. LP,SEWARD
1,AKA20049041,AK-99-99,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA
2,AKA20049041,AK-99-99,AK,EAGLE RIDGE OF PALMER,PALMER
3,AKA20049041,AK-99-99,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD
4,AKA20049041,AK-99-99,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN
...,...,...,...,...,...
37081,WYA20160004,WY-14-286,WY,WOLF CREEK APARTMENTS,RIVERTON
37082,NaN,WY-07-150,WY,WOODRIDGE APARTMENTS,RIVERTON
37083,NaN,WY-05-128,WY,WYOMING NATIONAL APTS,CASPER
37084,WYA20080035,WY-06-425,WY,YELLOW CREEK VILLAGE,EVANSTON
37085,NaN,WY-11-195,WY,YORK PLACE APARTMENTS,SHERIDAN

Columms 6-13 come from table 4.
HH = House Hold Head. Each row represents one apartment complex

In [148]:
#Create headofhouse data frame
headofhouse = housing_df[['state', 'propertyname' ,'city', 'HH_RACE_WHITE_PCT', 'HH_RACE_BLACK_PCT', 'HH_RACE_AMINDALNAT_PCT',
       'HH_RACE_ASIAN_PCT', 'HH_RACE_HAWAIIANPI_PCT', 'HH_RACE_OTHER_PCT',
       'HH_RACE_HISPANIC_PCT', 'HH_RACE_NR_PCT']]

#Renaming variables
headofhouse = headofhouse.rename(columns={"HH_RACE_WHITE_PCT": "White"})
headofhouse = headofhouse.rename(columns={"HH_RACE_BLACK_PCT": "BlackorAfricanAmerican"})
headofhouse = headofhouse.rename(columns={"HH_RACE_AMINDALNAT_PCT": "AmericanIndianorAlaskaNative"})
headofhouse = headofhouse.rename(columns={"HH_RACE_ASIAN_PCT": "Asian"})
headofhouse = headofhouse.rename(columns={"HH_RACE_HAWAIIANPI_PCT": "HawaiianorPacificIslander"})
headofhouse = headofhouse.rename(columns={"HH_RACE_OTHER_PCT": "OtherRace"})
headofhouse = headofhouse.rename(columns={"HH_RACE_HISPANIC_PCT": "Hispanic"})
headofhouse = headofhouse.rename(columns={"HH_RACE_NR_PCT": "Non_Reported"})

# Cleaning null values
for col in ['White', 'BlackorAfricanAmerican', 'AmericanIndianorAlaskaNative', 'Asian', 'HawaiianorPacificIslander', 'OtherRace', 'Hispanic', 'Non_Reported']:
    headofhouse[col] = headofhouse[col].replace(-4, np.nan)

headofhouse = headofhouse.dropna(axis = 0, how = 'any', subset = None)

headofhouse

#Data Visualization

,state,propertyname,city,White,BlackorAfricanAmerican,AmericanIndianorAlaskaNative,Asian,HawaiianorPacificIslander,OtherRace,Hispanic,Non_Reported
14,AK,SOUND VIEW ASSOCIATES,VALDEZ,100.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
31,AL,ALICEVILLE ESTATES,ALICEVILLE,0.000000,100.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
39,AL,ANNE PLACE,MOBILE,13.200000,70.300003,0.0,0.0,0.0,0.0,0.000000,16.500000
42,AL,APPALOOSA RUN,ANDALUSIA,55.599998,44.400002,0.0,0.0,0.0,0.0,0.000000,0.000000
47,AL,ARBOURS AT CANE CREEK F/K/A CANE CREEK APARTMENTS,ANNISTON,12.100000,50.000000,0.0,0.0,0.0,0.0,0.000000,37.900002
...,...,...,...,...,...,...,...,...,...,...,...
37048,WY,DESERT RUN II,GILLETTE,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,100.000000
37050,WY,ELKHORN APARTMENTS,CASPER,30.200001,0.000000,0.0,0.0,0.0,0.0,0.000000,69.800003
37089,WY,PIONEER HOMESTEAD II,JACKSON,100.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
37090,WY,PIONEER HOMESTEAD III,JACKSON,100.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
37109,WY,SHERIDAN SQUARE,SHERIDAN,39.400002,0.000000,0.0,0.0,0.0,0.0,28.200001,32.400002

Columns 14-20 come from Table 8

In [ ]:
#Create income data frame
household_income = housing_df[['state', 'propertyname' ,'city','MEDIAN_INC', 'INCOME_REPORTED_PCT', 'UNITS_INC_0_5K_PCT',
       'UNITS_INC_5K_10K_PCT', 'UNITS_INC_10K_15K_PCT', 'UNITS_INC_15_20K_PCT',
       'UNITS_INC_GRT_20K_PCT']]

#Rename varibles
household_income = household_income.rename(columns={"MEDIAN_INC": "MedianIncome"})
household_income = household_income.rename(columns={"INCOME_REPORTED_PCT": "IncomeReportedinPercent"})
household_income = household_income.rename(columns={"UNITS_INC_0_5K_PCT": "$0-$5000"})
household_income = household_income.rename(columns={"UNITS_INC_5K_10K_PCT": "$5000-$10000"})
household_income = household_income.rename(columns={"UNITS_INC_10K_15K_PCT": "$10000-$15000"})
household_income = household_income.rename(columns={"UNITS_INC_15_20K_PCT": "$15000-$20000"})
household_income = household_income.rename(columns={"UNITS_INC_GRT_20K_PCT": "$20000+"})

# Cleaning null values
for col in ['MedianIncome', 'IncomeReportedinPercent', '$0-$5000', '$5000-$10000', '$10000-$15000', '$15000-$20000', '$20000+']:
    household_income[col] = household_income[col].replace(-4, np.nan)

household_income = household_income.dropna(axis = 0, how = 'any', subset = None)
household_income

#Data Visualization

 Columns 21-26 come from table 9

In [ ]:
#Create income relative to Area Median Income
IncometoAmi = housing_df[['state', 'propertyname' ,'city','UNITS_I_IL_IR_0_PCT', 'UNITS_I_IL_IR_0_30_PCT',
       'UNITS_I_IL_IR_30_40_PCT', 'UNITS_I_IL_IR_40_50_PCT',
       'UNITS_I_IL_IR_50_60_PCT', 'UNITS_I_IL_IR_GT60_PCT']]
#Rename variables
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_0_PCT": "Unavailable"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_0_30_PCT": "0-30%"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_30_40_PCT": "30-40%"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_40_50_PCT": "40-50%"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_50_60_PCT": "50-60%"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_GT60_PCT": "60%+"})

# Cleaning null values
for col in ['Unavailable', '0-30%', '30-40%', '40-50%', '50-60%', '60%+']:
    IncometoAmi[col] = IncometoAmi[col].replace(-4, np.nan)

IncometoAmi = IncometoAmi.dropna(axis = 0, how = 'any', subset = None)

IncometoAmi

#Data Visualization

Columns 27-33 come from Table 10

In [149]:
#Create data frame
rentBurden = housing_df[['state', 'propertyname' ,'city','UNITS_INC_RNT_RPTD_PCT', 'UNITS_INC_RNT_0_PCT',
       'UNITS_INC_RNT_0_30_PCT', 'UNITS_INC_RNT_30_40_PCT',
       'UNITS_INC_RNT_40_50_PCT', 'UNITS_INC_RNT_GRT_50_PCT',
       'UNITS_INC_RNT_NOT_CAL_PCT']]

#Rename variables
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_RPTD_PCT": "IncomeAndRentRprt"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_0_PCT": "0%ofIncome"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_0_30_PCT": "0-30%ofIncome"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_30_40_PCT": "30-40%ofIncome"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_40_50_PCT": "40-50%ofIncome"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_GRT_50_PCT": "50%ofIncome+"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_NOT_CAL_PCT": "NotCalculated"})

# Cleaning null values
for col in ['IncomeAndRentRprt', '0%ofIncome', '0-30%ofIncome', '30-40%ofIncome', '40-50%ofIncome', '50%ofIncome+', 'NotCalculated']:
    rentBurden[col] = rentBurden[col].replace(-4, np.nan)

rentBurden = rentBurden.dropna(axis = 0, how = 'any', subset = None)

rentBurden

#Data Visualization

,state,propertyname,city,IncomeAndRentRprt,0%ofIncome,0-30%ofIncome,30-40%ofIncome,40-50%ofIncome,50%ofIncome+,NotCalculated
26,AL,AHEPA 310 APARTMENTS,MOBILE,100.000000,0.000000,100.000000,0.0,0.0,0.0,0.0
41,AL,APARTMENTS AT RUSSEL ERSKINE FKA RUSSEL ERSKIN...,HUNTSVILLE,100.000000,0.000000,100.000000,0.0,0.0,0.0,0.0
44,AL,ARBOR GATE APARTMENTS,BRIDGEPORT,100.000000,0.000000,100.000000,0.0,0.0,0.0,0.0
91,AL,BONAIRE VILLAS,PINE HILL,100.000000,0.000000,100.000000,0.0,0.0,0.0,0.0
93,AL,BRADLEY PARK APARTMENTS,ATTALLA,94.400002,55.900002,44.099998,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
37024,WY,CEDAR CREEK II APARTMENTS,JACKSON,96.300003,0.000000,100.000000,0.0,0.0,0.0,0.0
37045,WY,CRYSTAL COVE I,CODY,100.000000,0.000000,100.000000,0.0,0.0,0.0,0.0
37046,WY,CRYSTAL COVE II,CODY,100.000000,0.000000,100.000000,0.0,0.0,0.0,0.0
37065,WY,HOMESTEAD APARTMENTS,SHERIDAN,100.000000,0.000000,100.000000,0.0,0.0,0.0,0.0
37080,WY,PARKVIEW APARTMENTS I,POWELL,90.900002,0.000000,100.000000,0.0,0.0,0.0,0.0

Columns 34-36 come from Table 11

In [150]:
#Create date frame
rentalAsssitance =housing_df[['state', 'propertyname' ,'city','UNITS_RNTASSTNCE_MSNG_PCT', 'UNITS_RNTASSTNCE_RPTD_0_PCT',
       'UNITS_RNTASSTNCE_RPTD_GRT0_PCT']]

#Rename variables
rentalAsssitance = rentalAsssitance.rename(columns={"UNITS_RNTASSTNCE_MSNG_PCT": "Missing"})
rentalAsssitance = rentalAsssitance.rename(columns={"UNITS_RNTASSTNCE_RPTD_0_PCT": "NoAssitance"})
rentalAsssitance = rentalAsssitance.rename(columns={"UNITS_RNTASSTNCE_RPTD_GRT0_PCT": "SomeAssitance"})

# Cleaning null values
for col in ['Missing', 'NoAssitance', 'SomeAssitance']:
    rentalAsssitance[col] = rentalAsssitance[col].replace(-4, np.nan)

rentalAsssitance = rentalAsssitance.dropna(axis = 0, how = 'any', subset = None)

rentalAsssitance

#Data Visualization

,state,propertyname,city,Missing,NoAssitance,SomeAssitance
1,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,0.0,0.000000,100.000000
5,AK,HAMPSTEAD HEATH,ANCHORAGE,0.0,58.099998,41.900002
9,AK,"MILL BAY TOWNHOMES, LLC",KODIAK,0.0,69.199997,30.799999
10,AK,MLH MANOR,FAIRBANKS,0.0,45.700001,54.299999
12,AK,NORTHWARD BUILDING,FAIRBANKS,0.0,73.300003,26.700001
...,...,...,...,...,...,...
38199,WI,MADISON ON BROADWAY,MADISON,0.0,60.000000,40.000000
38203,WI,PARKVIEW COMMONS,SOMERS,0.0,80.199997,19.799999
38205,WI,RED CLIFF REHAB II,RUSSELL,0.0,100.000000,0.000000
38210,WV,GREENE GABLES,SHORT GAP,0.0,77.099998,22.900000
38227,WA,TEAL POINTE APARTMENTS,VANCOUVER,0.0,72.599998,27.400000

Columns 37-46 come from Table 12

In [151]:
#Create data frame
federalAssitenceSource = housing_df[['state', 'propertyname' ,'city','UNITS_FRA_RPTD_GRT0_PCT',
       'UNITS_FRA_SRC_PBRA_PCT', 'UNITS_FRA_SRC_S8_PCT',
       'UNITS_FRA_SRC_PH_PCT', 'UNITS_FRA_SRC_HOME_PCT',
       'UNITS_FRA_SRC_HCV_PCT', 'UNITS_FRA_SRC_PBV_PCT',
       'UNITS_FRA_SRC_S521_PCT', 'UNITS_FRA_SRC_OTHER_PCT',
       'UNITS_FRA_SRC_MSSNG_PCT']]

#Rename variables
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_RPTD_GRT0_PCT": "%withfederalAssitanceReported"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_PBRA_PCT": "Project-BasedRental"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_S8_PCT": "Section8"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_PH_PCT": "PublicHousing"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_HOME_PCT": "HOMEInvestment"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_HCV_PCT": "HousingChoiceVoucher"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_PBV_PCT": "ProjectBasedVoucher"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_S521_PCT": "Section521"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_OTHER_PCT": "Other"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_MSSNG_PCT": "Missing"})

# Cleaning null values
for col in ["%withfederalAssitanceReported", "Project-BasedRental", "Section8", "PublicHousing", "HOMEInvestment", "HousingChoiceVoucher", "ProjectBasedVoucher", "Section521", "Other", "Missing"]:
    federalAssitenceSource[col] = federalAssitenceSource[col].replace(-4, np.nan)

federalAssitenceSource = federalAssitenceSource.dropna(axis = 0, how = 'any', subset = None)

federalAssitenceSource

#Data Visualization

,state,propertyname,city,%withfederalAssitanceReported,Project-BasedRental,Section8,PublicHousing,HOMEInvestment,HousingChoiceVoucher,ProjectBasedVoucher,Section521,Other,Missing
0,AK,BAYVIEW APTS. ASSOC. LP,SEWARD,91.300003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
1,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,97.599998,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
2,AK,EAGLE RIDGE OF PALMER,PALMER,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD,95.500000,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
4,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN,97.800003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38206,WI,ST CROIX FALLS TOWNHOMES,ST CROIX FALLS,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38208,WV,ASHLEY MANOR APARTMENTS,RIPLEY,92.300003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
38209,WV,DUTCH RIDGE,DAVISVILLE,95.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
38210,WV,GREENE GABLES,SHORT GAP,22.900000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
38221,WV,SHOALS MANOR APARTMENTS,HUNTINGTON SHOALS,90.900002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0