<a href="https://colab.research.google.com/github/bitriagaleonela40-cmd/housing-research/blob/main/Housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [83]:
import pandas as pd

In [84]:
housing_df = pd.read_csv("/content/2022 LIHTC Full Tenant Data.csv")

I belive I have 38228 rows and 47 colunms

In [85]:
housing_df.head(14)
housing_df.shape
housing_df.columns[36:47]

Index(['UNITS_RNTASSTNCE_RPTD_GRT0_PCT', 'UNITS_FRA_RPTD_GRT0_PCT',
       'UNITS_FRA_SRC_PBRA_PCT', 'UNITS_FRA_SRC_S8_PCT',
       'UNITS_FRA_SRC_PH_PCT', 'UNITS_FRA_SRC_HOME_PCT',
       'UNITS_FRA_SRC_HCV_PCT', 'UNITS_FRA_SRC_PBV_PCT',
       'UNITS_FRA_SRC_S521_PCT', 'UNITS_FRA_SRC_OTHER_PCT',
       'UNITS_FRA_SRC_MSSNG_PCT'],
      dtype='object')

Interpeting the first five rows
I learned that .xlsx stands for a excel file and therefore I cannot use read_csv. Instead I can use pd.read_excel to load in my data set. Looking at this data set, Im noticing that it mathces my housing_df, the only difference is it does not include any varibles past city. This can be useful if I want to limit myself to look at only  thouse variables.

Colums 1-5 in the housing_df come from this df.

In [86]:
url = "https://github.com/frontiertechinstitute/datasets/raw/main/2022%20LIHTC%20Tenant%20Data/data/2022%20LIHTC%20Tenant%20Data%20by%20Property%20-%20HUD_ID.xlsx"
df = pd.read_excel(url)
df.head(10)
df[['matching_hud_id', 'pin', 'state', 'propertyname', 'city']]

,matching_hud_id,pin,state,propertyname,city
0,AKA20049041,AK-99-99,AK,BAYVIEW APTS. ASSOC. LP,SEWARD
1,AKA20049041,AK-99-99,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA
2,AKA20049041,AK-99-99,AK,EAGLE RIDGE OF PALMER,PALMER
3,AKA20049041,AK-99-99,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD
4,AKA20049041,AK-99-99,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN
...,...,...,...,...,...
37081,WYA20160004,WY-14-286,WY,WOLF CREEK APARTMENTS,RIVERTON
37082,NaN,WY-07-150,WY,WOODRIDGE APARTMENTS,RIVERTON
37083,NaN,WY-05-128,WY,WYOMING NATIONAL APTS,CASPER
37084,WYA20080035,WY-06-425,WY,YELLOW CREEK VILLAGE,EVANSTON
37085,NaN,WY-11-195,WY,YORK PLACE APARTMENTS,SHERIDAN

Now Im gonna look at columms 6-13 which are correspondent to table 4.
Observation and Documentation info:

In [87]:
housing_df[['HH_RACE_WHITE_PCT', 'HH_RACE_BLACK_PCT', 'HH_RACE_AMINDALNAT_PCT',
       'HH_RACE_ASIAN_PCT', 'HH_RACE_HAWAIIANPI_PCT', 'HH_RACE_OTHER_PCT',
       'HH_RACE_HISPANIC_PCT', 'HH_RACE_NR_PCT']]

,HH_RACE_WHITE_PCT,HH_RACE_BLACK_PCT,HH_RACE_AMINDALNAT_PCT,HH_RACE_ASIAN_PCT,HH_RACE_HAWAIIANPI_PCT,HH_RACE_OTHER_PCT,HH_RACE_HISPANIC_PCT,HH_RACE_NR_PCT
0,91.300003,-4.0,-4.0,0.0,0.0,0.0,0.0,0.0
1,46.299999,-4.0,-4.0,-4.0,0.0,0.0,-4.0,-4.0
2,87.500000,-4.0,-4.0,0.0,0.0,0.0,-4.0,-4.0
3,90.900002,-4.0,0.0,0.0,0.0,0.0,0.0,-4.0
4,76.099998,-4.0,-4.0,-4.0,0.0,0.0,-4.0,0.0
...,...,...,...,...,...,...,...,...
38223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Now Im gonna look at Columns 14-20 which come from Table 8

In [88]:
housing_df[['MEDIAN_INC', 'INCOME_REPORTED_PCT', 'UNITS_INC_0_5K_PCT',
       'UNITS_INC_5K_10K_PCT', 'UNITS_INC_10K_15K_PCT', 'UNITS_INC_15_20K_PCT',
       'UNITS_INC_GRT_20K_PCT']]

,MEDIAN_INC,INCOME_REPORTED_PCT,UNITS_INC_0_5K_PCT,UNITS_INC_5K_10K_PCT,UNITS_INC_10K_15K_PCT,UNITS_INC_15_20K_PCT,UNITS_INC_GRT_20K_PCT
0,16644.0,100.000000,-4.0,-4.0,-4.0,-4.0,-4.000000
1,21922.0,92.699997,-4.0,-4.0,-4.0,-4.0,55.299999
2,34729.0,100.000000,-4.0,0.0,0.0,-4.0,67.500000
3,17890.0,100.000000,-4.0,0.0,-4.0,50.0,34.099998
4,16617.0,100.000000,-4.0,-4.0,-4.0,50.0,23.900000
...,...,...,...,...,...,...,...
38223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38224,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38225,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38226,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38227,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Now Columns 21-26 come from Table 9

In [89]:
housing_df[['UNITS_I_IL_IR_0_PCT', 'UNITS_I_IL_IR_0_30_PCT',
       'UNITS_I_IL_IR_30_40_PCT', 'UNITS_I_IL_IR_40_50_PCT',
       'UNITS_I_IL_IR_50_60_PCT', 'UNITS_I_IL_IR_GT60_PCT']]

,UNITS_I_IL_IR_0_PCT,UNITS_I_IL_IR_0_30_PCT,UNITS_I_IL_IR_30_40_PCT,UNITS_I_IL_IR_40_50_PCT,UNITS_I_IL_IR_50_60_PCT,UNITS_I_IL_IR_GT60_PCT
0,0.0,63.599998,-4.0,-4.0,0.0,-4.0
1,0.0,55.299999,-4.0,-4.0,-4.0,-4.0
2,-4.0,32.500000,-4.0,-4.0,-4.0,-4.0
3,-4.0,68.199997,-4.0,-4.0,-4.0,0.0
4,0.0,82.199997,-4.0,-4.0,0.0,-4.0
...,...,...,...,...,...,...
38223,-4.0,-4.000000,-4.0,-4.0,-4.0,-4.0
38224,NaN,NaN,NaN,NaN,NaN,NaN
38225,NaN,NaN,NaN,NaN,NaN,NaN
38226,NaN,NaN,NaN,NaN,NaN,NaN
38227,NaN,NaN,NaN,NaN,NaN,NaN

Columns 27-33 come from Table 10

In [90]:
housing_df[['UNITS_INC_RNT_RPTD_PCT', 'UNITS_INC_RNT_0_PCT',
       'UNITS_INC_RNT_0_30_PCT', 'UNITS_INC_RNT_30_40_PCT',
       'UNITS_INC_RNT_40_50_PCT', 'UNITS_INC_RNT_GRT_50_PCT',
       'UNITS_INC_RNT_NOT_CAL_PCT']]

,UNITS_INC_RNT_RPTD_PCT,UNITS_INC_RNT_0_PCT,UNITS_INC_RNT_0_30_PCT,UNITS_INC_RNT_30_40_PCT,UNITS_INC_RNT_40_50_PCT,UNITS_INC_RNT_GRT_50_PCT,UNITS_INC_RNT_NOT_CAL_PCT
0,100.000000,0.0,-4.0,0.0,0.0,0.0,-4.0
1,92.699997,0.0,-4.0,0.0,-4.0,0.0,0.0
2,100.000000,0.0,47.5,-4.0,-4.0,-4.0,-4.0
3,100.000000,0.0,-4.0,0.0,0.0,0.0,-4.0
4,100.000000,0.0,-4.0,0.0,0.0,0.0,-4.0
...,...,...,...,...,...,...,...
38223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38224,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38225,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38226,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38227,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Columns 34-36 come from Table 11

In [91]:
housing_df[['UNITS_RNTASSTNCE_MSNG_PCT', 'UNITS_RNTASSTNCE_RPTD_0_PCT',
       'UNITS_RNTASSTNCE_RPTD_GRT0_PCT']]

,UNITS_RNTASSTNCE_MSNG_PCT,UNITS_RNTASSTNCE_RPTD_0_PCT,UNITS_RNTASSTNCE_RPTD_GRT0_PCT
0,0.0,-4.000000,-4.0
1,0.0,0.000000,100.0
2,0.0,-4.000000,-4.0
3,0.0,-4.000000,-4.0
4,0.0,-4.000000,-4.0
...,...,...,...
38223,-4.0,-4.000000,-4.0
38224,-4.0,0.000000,-4.0
38225,-4.0,0.000000,-4.0
38226,-4.0,0.000000,-4.0
38227,0.0,72.599998,27.4

Columns 37-46 come from Table 12

In [92]:
housing_df[['UNITS_RNTASSTNCE_RPTD_GRT0_PCT', 'UNITS_FRA_RPTD_GRT0_PCT',
       'UNITS_FRA_SRC_PBRA_PCT', 'UNITS_FRA_SRC_S8_PCT',
       'UNITS_FRA_SRC_PH_PCT', 'UNITS_FRA_SRC_HOME_PCT',
       'UNITS_FRA_SRC_HCV_PCT', 'UNITS_FRA_SRC_PBV_PCT',
       'UNITS_FRA_SRC_S521_PCT', 'UNITS_FRA_SRC_OTHER_PCT',
       'UNITS_FRA_SRC_MSSNG_PCT']]

,UNITS_RNTASSTNCE_RPTD_GRT0_PCT,UNITS_FRA_RPTD_GRT0_PCT,UNITS_FRA_SRC_PBRA_PCT,UNITS_FRA_SRC_S8_PCT,UNITS_FRA_SRC_PH_PCT,UNITS_FRA_SRC_HOME_PCT,UNITS_FRA_SRC_HCV_PCT,UNITS_FRA_SRC_PBV_PCT,UNITS_FRA_SRC_S521_PCT,UNITS_FRA_SRC_OTHER_PCT,UNITS_FRA_SRC_MSSNG_PCT
0,-4.0,91.300003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
1,100.0,97.599998,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
2,-4.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-4.0,95.500000,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
4,-4.0,97.800003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
38223,-4.0,-4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38224,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38225,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38226,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38227,27.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN