<a href="https://colab.research.google.com/github/bitriagaleonela40-cmd/housing-research/blob/main/Housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [33]:
import pandas as pd

In [34]:
housing_df = pd.read_csv("/content/2022 LIHTC Full Tenant Data.csv")

I have 38228 rows and 47 columms.
I-----------> rows
I
I
I
I
+
colummns

In [58]:
housing_df.head(14)
housing_df.shape

(38228, 47)

Interpeting the first five rows
I learned that .xlsx stands for a excel file and therefore I cannot use read_csv. Instead I can use pd.read_excel to load in my data set. Looking at this data set, Im noticing that it mathces my housing_df, the only difference is it does not include any varibles past city. This can be useful if I want to limit myself to look at only  thouse variables.

In [44]:
url = "https://github.com/frontiertechinstitute/datasets/raw/main/2022%20LIHTC%20Tenant%20Data/data/2022%20LIHTC%20Tenant%20Data%20by%20Property%20-%20HUD_ID.xlsx"
df = pd.read_excel(url)
df.head(10)

,matching_hud_id,pin,state,propertyname,city
0,AKA20049041,AK-99-99,AK,BAYVIEW APTS. ASSOC. LP,SEWARD
1,AKA20049041,AK-99-99,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA
2,AKA20049041,AK-99-99,AK,EAGLE RIDGE OF PALMER,PALMER
3,AKA20049041,AK-99-99,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD
4,AKA20049041,AK-99-99,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN
5,AKA20183035,AK18-00021,AK,HAMPSTEAD HEATH,ANCHORAGE
6,AKA20049041,AK-99-99,AK,"HARBOR RIDGE-HOMER ASSOCIATES, LLC",HOMER
7,AKA20049041,AK-99-99,AK,"HUNTER CREEK APTS. OF PALMER, LP",PALMER
8,AKA19949001,AK-92-0033,AK,LOUSSAC-SOGN,ANCHORAGE
9,AKA20049041,AK-99-99,AK,"MILL BAY TOWNHOMES, LLC",KODIAK

Now Im gonna look at columms 6-13
Observation and Documentation info:
Table 4 shows the percentage of reported heads of household for whom race and ethnicity were
submitted to HUD. Table 4b provides the same information for all reported household members. The
first column repeats the percentage of properties reported from Table 2 to provide perspective on the
completeness for the entire active LIHTC stock in each state.

In [54]:
housing_df.iloc[6:14]

,Unnamed: 0,matching_hud_id,pin,state,propertyname,city,HH_RACE_WHITE_PCT,HH_RACE_BLACK_PCT,HH_RACE_AMINDALNAT_PCT,HH_RACE_ASIAN_PCT,...,UNITS_FRA_RPTD_GRT0_PCT,UNITS_FRA_SRC_PBRA_PCT,UNITS_FRA_SRC_S8_PCT,UNITS_FRA_SRC_PH_PCT,UNITS_FRA_SRC_HOME_PCT,UNITS_FRA_SRC_HCV_PCT,UNITS_FRA_SRC_PBV_PCT,UNITS_FRA_SRC_S521_PCT,UNITS_FRA_SRC_OTHER_PCT,UNITS_FRA_SRC_MSSNG_PCT
6,7,AKA20049041,AK-99-99,AK,"HARBOR RIDGE-HOMER ASSOCIATES, LLC",HOMER,-4.000000,0.0,-4.0,0.0,...,91.099998,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
7,8,AKA20049041,AK-99-99,AK,"HUNTER CREEK APTS. OF PALMER, LP",PALMER,89.300003,-4.0,-4.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9,AKA19949001,AK-92-0033,AK,LOUSSAC-SOGN,ANCHORAGE,26.500000,-4.0,-4.0,-4.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10,AKA20049041,AK-99-99,AK,"MILL BAY TOWNHOMES, LLC",KODIAK,-4.000000,0.0,-4.0,-4.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,11,AKA19960025,AK-99-99,AK,MLH MANOR,FAIRBANKS,65.699997,0.0,-4.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12,AKA20049041,AK-99-99,AK,"MUNAQSRI SENIOR ASSOC. OF NOME, LLC",NOME,-4.000000,0.0,-4.0,0.0,...,95.000000,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
12,13,AKA20010025,AK99-00009,AK,NORTHWARD BUILDING,FAIRBANKS,25.299999,-4.0,-4.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,14,AKA20030035,AK-99-99,AK,PARKVIEW-SOLDOTNA ASSOCIATES LP,SOLDOTNA,-4.000000,0.0,0.0,0.0,...,87.500000,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0