<a href="https://colab.research.google.com/github/bitriagaleonela40-cmd/housing-research/blob/main/Housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [50]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [51]:
housing_df = pd.read_csv("/content/2022 LIHTC Full Tenant Data.csv")
housing_df.head(5)

,Unnamed: 0,matching_hud_id,pin,state,propertyname,city,HH_RACE_WHITE_PCT,HH_RACE_BLACK_PCT,HH_RACE_AMINDALNAT_PCT,HH_RACE_ASIAN_PCT,...,UNITS_FRA_RPTD_GRT0_PCT,UNITS_FRA_SRC_PBRA_PCT,UNITS_FRA_SRC_S8_PCT,UNITS_FRA_SRC_PH_PCT,UNITS_FRA_SRC_HOME_PCT,UNITS_FRA_SRC_HCV_PCT,UNITS_FRA_SRC_PBV_PCT,UNITS_FRA_SRC_S521_PCT,UNITS_FRA_SRC_OTHER_PCT,UNITS_FRA_SRC_MSSNG_PCT
0,1,AKA20049041,AK-99-99,AK,BAYVIEW APTS. ASSOC. LP,SEWARD,91.300003,-4.0,-4.0,0.0,...,91.300003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
1,2,AKA20049041,AK-99-99,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,46.299999,-4.0,-4.0,-4.0,...,97.599998,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
2,3,AKA20049041,AK-99-99,AK,EAGLE RIDGE OF PALMER,PALMER,87.500000,-4.0,-4.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,AKA20049041,AK-99-99,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD,90.900002,-4.0,0.0,0.0,...,95.500000,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
4,5,AKA20049041,AK-99-99,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN,76.099998,-4.0,-4.0,-4.0,...,97.800003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0

I belive I have 38228 rows and 47 colunms

Interpeting the first five rows
I learned that .xlsx stands for a excel file and therefore I cannot use read_csv. Instead I can use pd.read_excel to load in my data set. Looking at this data set, Im noticing that it mathces my housing_df, the only difference is it does not include any varibles past city. This can be useful if I want to limit myself to look at only  thouse variables.

Data sets can help investors to gauge assistance need and then invest.

Colums 1-5 in the housing_df come from this df.

In [52]:
url = "https://github.com/frontiertechinstitute/datasets/raw/main/2022%20LIHTC%20Tenant%20Data/data/2022%20LIHTC%20Tenant%20Data%20by%20Property%20-%20HUD_ID.xlsx"
df = pd.read_excel(url)
df.head(5)
df[['matching_hud_id', 'pin', 'state', 'propertyname', 'city']]

,matching_hud_id,pin,state,propertyname,city
0,AKA20049041,AK-99-99,AK,BAYVIEW APTS. ASSOC. LP,SEWARD
1,AKA20049041,AK-99-99,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA
2,AKA20049041,AK-99-99,AK,EAGLE RIDGE OF PALMER,PALMER
3,AKA20049041,AK-99-99,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD
4,AKA20049041,AK-99-99,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN
...,...,...,...,...,...
37081,WYA20160004,WY-14-286,WY,WOLF CREEK APARTMENTS,RIVERTON
37082,NaN,WY-07-150,WY,WOODRIDGE APARTMENTS,RIVERTON
37083,NaN,WY-05-128,WY,WYOMING NATIONAL APTS,CASPER
37084,WYA20080035,WY-06-425,WY,YELLOW CREEK VILLAGE,EVANSTON
37085,NaN,WY-11-195,WY,YORK PLACE APARTMENTS,SHERIDAN

Columms 6-13 come from table 4.
HH = House Hold Head. Each row represents one apartment complex

In [53]:
#Create headofhouse data frame
headofhouse = housing_df[['state', 'propertyname' ,'city', 'HH_RACE_WHITE_PCT', 'HH_RACE_BLACK_PCT', 'HH_RACE_AMINDALNAT_PCT',
       'HH_RACE_ASIAN_PCT', 'HH_RACE_HAWAIIANPI_PCT', 'HH_RACE_OTHER_PCT',
       'HH_RACE_HISPANIC_PCT', 'HH_RACE_NR_PCT']]

#Renaming variables
headofhouse = headofhouse.rename(columns={"HH_RACE_WHITE_PCT": "White"})
headofhouse = headofhouse.rename(columns={"HH_RACE_BLACK_PCT": "BlackorAfricanAmerican"})
headofhouse = headofhouse.rename(columns={"HH_RACE_AMINDALNAT_PCT": "AmericanIndianorAlaskaNative"})
headofhouse = headofhouse.rename(columns={"HH_RACE_ASIAN_PCT": "Asian"})
headofhouse = headofhouse.rename(columns={"HH_RACE_HAWAIIANPI_PCT": "HawaiianorPacificIslander"})
headofhouse = headofhouse.rename(columns={"HH_RACE_OTHER_PCT": "OtherRace"})
headofhouse = headofhouse.rename(columns={"HH_RACE_HISPANIC_PCT": "Hispanic"})
headofhouse = headofhouse.rename(columns={"HH_RACE_NR_PCT": "Non_Reported"})
headofhouse

#Cleaning null values


#Data Visualization

,state,propertyname,city,White,BlackorAfricanAmerican,AmericanIndianorAlaskaNative,Asian,HawaiianorPacificIslander,OtherRace,Hispanic,Non_Reported
0,AK,BAYVIEW APTS. ASSOC. LP,SEWARD,91.300003,-4.0,-4.0,0.0,0.0,0.0,0.0,0.0
1,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,46.299999,-4.0,-4.0,-4.0,0.0,0.0,-4.0,-4.0
2,AK,EAGLE RIDGE OF PALMER,PALMER,87.500000,-4.0,-4.0,0.0,0.0,0.0,-4.0,-4.0
3,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD,90.900002,-4.0,0.0,0.0,0.0,0.0,0.0,-4.0
4,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN,76.099998,-4.0,-4.0,-4.0,0.0,0.0,-4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
38223,WY,PINEWOOD APARTMENTS,MARBLETON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38224,NM,PASA TIEMPO,SANTE FE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38225,SD,SICANGU VILLAGE ESTATES III,VALENTINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38226,VA,BICKERSTAFF CROSSING,HENRICO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38227,WA,TEAL POINTE APARTMENTS,VANCOUVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Columns 14-20 come from Table 8

In [54]:
#Create income data frame
household_income = housing_df[['state', 'propertyname' ,'city','MEDIAN_INC', 'INCOME_REPORTED_PCT', 'UNITS_INC_0_5K_PCT',
       'UNITS_INC_5K_10K_PCT', 'UNITS_INC_10K_15K_PCT', 'UNITS_INC_15_20K_PCT',
       'UNITS_INC_GRT_20K_PCT']]

#Rename varibles
household_income = household_income.rename(columns={"MEDIAN_INC": "MedianIncome"})
household_income = household_income.rename(columns={"INCOME_REPORTED_PCT": "IncomeReportedinPercent"})
household_income = household_income.rename(columns={"UNITS_INC_0_5K_PCT": "$0-$5000"})
household_income = household_income.rename(columns={"UNITS_INC_5K_10K_PCT": "$5000-$10000"})
household_income = household_income.rename(columns={"UNITS_INC_10K_15K_PCT": "$10000-$15000"})
household_income = household_income.rename(columns={"UNITS_INC_15_20K_PCT": "$15000-$20000"})
household_income = household_income.rename(columns={"UNITS_INC_GRT_20K_PCT": "$20000+"})
household_income = household_income.dropna(axis = 0, how = 'any', subset = None)
household_income

#Cleaning null values

#Data Visualization

,state,propertyname,city,MedianIncome,IncomeReportedinPercent,$0-$5000,$5000-$10000,$10000-$15000,$15000-$20000,$20000+
0,AK,BAYVIEW APTS. ASSOC. LP,SEWARD,16644.0,100.000000,-4.0,-4.0,-4.000000,-4.0,-4.000000
1,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,21922.0,92.699997,-4.0,-4.0,-4.000000,-4.0,55.299999
2,AK,EAGLE RIDGE OF PALMER,PALMER,34729.0,100.000000,-4.0,0.0,0.000000,-4.0,67.500000
3,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD,17890.0,100.000000,-4.0,0.0,-4.000000,50.0,34.099998
4,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN,16617.0,100.000000,-4.0,-4.0,-4.000000,50.0,23.900000
...,...,...,...,...,...,...,...,...,...,...
37123,WY,WOLF CREEK APARTMENTS,RIVERTON,-4.0,-4.000000,-4.0,-4.0,-4.000000,-4.0,-4.000000
37124,WY,WOODRIDGE APARTMENTS,RIVERTON,27859.0,100.000000,-4.0,-4.0,-4.000000,-4.0,63.900002
37125,WY,WYOMING NATIONAL APTS,CASPER,13536.0,100.000000,-4.0,-4.0,38.200001,-4.0,41.200001
37126,WY,YELLOW CREEK VILLAGE,EVANSTON,29062.0,100.000000,0.0,0.0,-4.000000,-4.0,77.099998
37127,WY,YORK PLACE APARTMENTS,SHERIDAN,20694.0,100.000000,-4.0,0.0,-4.000000,-4.0,-4.000000

 Columns 21-26 come from table 9

In [55]:
#Create income relative to Area Median Income
IncometoAmi = housing_df[['state', 'propertyname' ,'city','UNITS_I_IL_IR_0_PCT', 'UNITS_I_IL_IR_0_30_PCT',
       'UNITS_I_IL_IR_30_40_PCT', 'UNITS_I_IL_IR_40_50_PCT',
       'UNITS_I_IL_IR_50_60_PCT', 'UNITS_I_IL_IR_GT60_PCT']]
#Rename variables
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_0_PCT": "Unavailable"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_0_30_PCT": "0-30%"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_30_40_PCT": "30-40%"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_40_50_PCT": "40-50%"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_50_60_PCT": "50-60%"})
IncometoAmi = IncometoAmi.rename(columns={"UNITS_I_IL_IR_GT60_PCT": "60%+"})
IncometoAmi

#Cleaning null values


#Data Visualization

,state,propertyname,city,Unavailable,0-30%,30-40%,40-50%,50-60%,60%+
0,AK,BAYVIEW APTS. ASSOC. LP,SEWARD,0.0,63.599998,-4.0,-4.0,0.0,-4.0
1,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,0.0,55.299999,-4.0,-4.0,-4.0,-4.0
2,AK,EAGLE RIDGE OF PALMER,PALMER,-4.0,32.500000,-4.0,-4.0,-4.0,-4.0
3,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD,-4.0,68.199997,-4.0,-4.0,-4.0,0.0
4,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN,0.0,82.199997,-4.0,-4.0,0.0,-4.0
...,...,...,...,...,...,...,...,...,...
38223,WY,PINEWOOD APARTMENTS,MARBLETON,-4.0,-4.000000,-4.0,-4.0,-4.0,-4.0
38224,NM,PASA TIEMPO,SANTE FE,NaN,NaN,NaN,NaN,NaN,NaN
38225,SD,SICANGU VILLAGE ESTATES III,VALENTINE,NaN,NaN,NaN,NaN,NaN,NaN
38226,VA,BICKERSTAFF CROSSING,HENRICO,NaN,NaN,NaN,NaN,NaN,NaN
38227,WA,TEAL POINTE APARTMENTS,VANCOUVER,NaN,NaN,NaN,NaN,NaN,NaN

Columns 27-33 come from Table 10

In [56]:
#Create data frame
rentBurden = housing_df[['state', 'propertyname' ,'city','UNITS_INC_RNT_RPTD_PCT', 'UNITS_INC_RNT_0_PCT',
       'UNITS_INC_RNT_0_30_PCT', 'UNITS_INC_RNT_30_40_PCT',
       'UNITS_INC_RNT_40_50_PCT', 'UNITS_INC_RNT_GRT_50_PCT',
       'UNITS_INC_RNT_NOT_CAL_PCT']]

#Rename variables
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_RPTD_PCT": "IncomeAndRentRprt"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_0_PCT": "0%ofIncome"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_0_30_PCT": "0-30%ofIncome"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_30_40_PCT": "30-40%ofIncome"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_40_50_PCT": "40-50%ofIncome"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_GRT_50_PCT": "50%ofIncome+"})
rentBurden = rentBurden.rename(columns={"UNITS_INC_RNT_NOT_CAL_PCT": "NotCalculated"})
rentBurden

#Cleaning null values

#Data Visualization

,state,propertyname,city,IncomeAndRentRprt,0%ofIncome,0-30%ofIncome,30-40%ofIncome,40-50%ofIncome,50%ofIncome+,NotCalculated
0,AK,BAYVIEW APTS. ASSOC. LP,SEWARD,100.000000,0.0,-4.0,0.0,0.0,0.0,-4.0
1,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,92.699997,0.0,-4.0,0.0,-4.0,0.0,0.0
2,AK,EAGLE RIDGE OF PALMER,PALMER,100.000000,0.0,47.5,-4.0,-4.0,-4.0,-4.0
3,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD,100.000000,0.0,-4.0,0.0,0.0,0.0,-4.0
4,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN,100.000000,0.0,-4.0,0.0,0.0,0.0,-4.0
...,...,...,...,...,...,...,...,...,...,...
38223,WY,PINEWOOD APARTMENTS,MARBLETON,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38224,NM,PASA TIEMPO,SANTE FE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38225,SD,SICANGU VILLAGE ESTATES III,VALENTINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38226,VA,BICKERSTAFF CROSSING,HENRICO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38227,WA,TEAL POINTE APARTMENTS,VANCOUVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Columns 34-36 come from Table 11

In [57]:
#Create date frame
rentalAsssitance = housing_df[['state', 'propertyname' ,'city','UNITS_RNTASSTNCE_MSNG_PCT', 'UNITS_RNTASSTNCE_RPTD_0_PCT',
       'UNITS_RNTASSTNCE_RPTD_GRT0_PCT']]

#Rename variables
rentalAsssitance = rentalAsssitance.rename(columns={"UNITS_RNTASSTNCE_MSNG_PCT": "Missing"})
rentalAsssitance = rentalAsssitance.rename(columns={"UNITS_RNTASSTNCE_RPTD_0_PCT": "NoAssitance"})
rentalAsssitance = rentalAsssitance.rename(columns={"UNITS_RNTASSTNCE_RPTD_GRT0_PCT": "SomeAssitance"})
rentalAsssitance

#Cleaning null values

#Data Visualization

,state,propertyname,city,Missing,NoAssitance,SomeAssitance
0,AK,BAYVIEW APTS. ASSOC. LP,SEWARD,0.0,-4.000000,-4.0
1,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,0.0,0.000000,100.0
2,AK,EAGLE RIDGE OF PALMER,PALMER,0.0,-4.000000,-4.0
3,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD,0.0,-4.000000,-4.0
4,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN,0.0,-4.000000,-4.0
...,...,...,...,...,...,...
38223,WY,PINEWOOD APARTMENTS,MARBLETON,-4.0,-4.000000,-4.0
38224,NM,PASA TIEMPO,SANTE FE,-4.0,0.000000,-4.0
38225,SD,SICANGU VILLAGE ESTATES III,VALENTINE,-4.0,0.000000,-4.0
38226,VA,BICKERSTAFF CROSSING,HENRICO,-4.0,0.000000,-4.0
38227,WA,TEAL POINTE APARTMENTS,VANCOUVER,0.0,72.599998,27.4

Columns 37-46 come from Table 12

In [58]:
#Create data frame
federalAssitenceSource = housing_df[['state', 'propertyname' ,'city','UNITS_FRA_RPTD_GRT0_PCT',
       'UNITS_FRA_SRC_PBRA_PCT', 'UNITS_FRA_SRC_S8_PCT',
       'UNITS_FRA_SRC_PH_PCT', 'UNITS_FRA_SRC_HOME_PCT',
       'UNITS_FRA_SRC_HCV_PCT', 'UNITS_FRA_SRC_PBV_PCT',
       'UNITS_FRA_SRC_S521_PCT', 'UNITS_FRA_SRC_OTHER_PCT',
       'UNITS_FRA_SRC_MSSNG_PCT']]

#Rename variables
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_RPTD_GRT0_PCT": "%withfederalAssitanceReported"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_PBRA_PCT": "Project-BasedRental"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_S8_PCT": "Section8"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_PH_PCT": "PublicHousing"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_HOME_PCT": "HOMEInvestment"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_HCV_PCT": "HousingChoiceVoucher"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_PBV_PCT": "ProjectBasedVoucher"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_S521_PCT": "Section521"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_OTHER_PCT": "Other"})
federalAssitenceSource = federalAssitenceSource.rename(columns={"UNITS_FRA_SRC_MSSNG_PCT": "Missing"})
federalAssitenceSource

#Cleaning null values


#Data Visualization

,state,propertyname,city,%withfederalAssitanceReported,Project-BasedRental,Section8,PublicHousing,HOMEInvestment,HousingChoiceVoucher,ProjectBasedVoucher,Section521,Other,Missing
0,AK,BAYVIEW APTS. ASSOC. LP,SEWARD,91.300003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
1,AK,"CORDOVA MEWS ASSOC. OF CORDOVA, LLC",CORDOVA,97.599998,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
2,AK,EAGLE RIDGE OF PALMER,PALMER,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AK,"GATEWAY-SEWARD ASSOCIATES, LTD PTN",SEWARD,95.500000,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
4,AK,GLACIER PARK-KETCHIKAN ASSOC. LP,KETCHIKAN,97.800003,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38223,WY,PINEWOOD APARTMENTS,MARBLETON,-4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38224,NM,PASA TIEMPO,SANTE FE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38225,SD,SICANGU VILLAGE ESTATES III,VALENTINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38226,VA,BICKERSTAFF CROSSING,HENRICO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38227,WA,TEAL POINTE APARTMENTS,VANCOUVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN